# Generated by Django 4.2.1 on 2025-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0002_category_alter_pizzashop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzashop',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
