# Generated by Django 4.2.1 on 2025-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0003_pizzashop_slug_alter_pizzashop_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
