# Generated by Django 4.2.1 on 2025-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0004_alter_pizzashop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
