# Generated by Django 4.2.1 on 2025-03-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0005_category_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzashop.category'),
        ),
    ]
