# Generated by Django 4.2.1 on 2025-03-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0006_alter_pizzashop_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
    ]
