# Generated by Django 4.2.1 on 2025-04-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0008_ostrota_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ostrota',
            old_name='name',
            new_name='lvl',
        ),
        migrations.RemoveField(
            model_name='ostrota',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ostrota',
            name='m_count',
        ),
    ]
