# Generated by Django 4.2.1 on 2025-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0009_rename_name_ostrota_lvl_remove_ostrota_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostrota',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Уровень остроты'),
        ),
    ]
